time = ('Flamengo', 'Santos', 'Palmeiras', 'Grêmio', 'Atheltico- PR', 'São Paulo', 'Internacional', 'Corinthians', 'Fortaleza', 'Goiás', 'Bahia', 'Vasco da Gama', 'Atlético - MG', 'Fluminense', 'Botafogo', 'Ceará SC', 'Cruzeiro', 'CSA', 'Chapecoense', 'Avaí')
print('-='*50)
print(f'Os cinco primeiros times são: {time[:5]}.')
print('-='*50)
print(f'Os quatro últimos times foram {time[-4:]}.')
print('-='*50)
print(f'Times em ordem alfabética: {sorted(time)}')
print('-='*50)
print(f'A Chapecoense está na {time.index("Chapecoense")+1}º posição')
print('-='*50)